// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import ()

type Account struct {
	ID       int64  `json:"-"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
