# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name pogongdb


    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Restore PostgreSQL database
      uses: docker://postgres:15.2-alpine
      with:
        entrypoint: /bin/bash
        args: -c "cat ./pg/backup.sql | docker exec -i $(CONTAINER_DB) psql -U postgres -d pogong"
      env:
        CONTAINER_DB: postgres

    - name: Test
      run: make test
